/* Flowers */
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Agapanthus, (each)",1.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Allium, Drumstick",0.63,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Alstromeria",0.66,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Amaranthus, Hanging (5 stem)",1.25,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Amaranthus, Upright  (5 stem)",1.25,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Artichokes (each)",4.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Asclepius",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Aspidistra",0.45,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Beargrass (20 stem)",0.11,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Beauty Aster",1.30,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Beauty Berry",1.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bells of Ireland",0.90,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bird of Paradise (each)",2.25,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bittersweet (5 stem)",3.20,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Boxwood",0.97,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Broom Corn",1.45,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bupleurum",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bush Ivy",0.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Calla Lily",2.80,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Calla Lily, mini",3.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Carnation, Red (25 stem)",0.39,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Carnation, White (25 stem)",0.39,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Carnations, Assorted (25 stem)",0.45,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Carnations, Pink (25 stem)",0.39,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cherry Blossom",1.05,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Christmas Bush",1.09,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cockscomb",0.68,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Coffee",0.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Coneflower",0.65,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cosmos, chocolate",1.40,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cotinus",1.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Craspedia",0.69,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cremon",0.58,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Curly Willow",14.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cymbidium  (each)",2.59,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cymbidium Spray",22.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Daffodil",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Dahlias",0.98,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Daisy",0.35,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Date Palm",0.80,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Delphinium",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Dendrobium (each)",29.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Dianthus",0.59,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Elegia",1.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Emerald (20 stem)",0.19,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Eremurus",1.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Euc, seeded",0.85,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Eucalyptus, baby ",0.75,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Eucomis, Pineapple Flower",2.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Feather fern",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Flatfern (Sword Fern) (20 stem)",0.28,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Football mums",0.85,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Forsythia",1.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Foxtail Fern",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Freesia",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Galax (100 stem)",19.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Gerberas",0.92,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Gerberas, Mini",1.06,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ginestra",1.20,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ginger (each)",4.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Gladiolus",1.22,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Godetia",0.54,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Grevillea",0.85,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Heather",0.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Horsetail",0.45,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Huckleberry",0.53,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Hydrandgea (each)",3.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Hypericum",0.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Iris",0.80,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Kale, ornamental (each)",2.15,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Kangaroo Paws",1.35,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Larkspur",1.02,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Leatherleaf, 25 pack",2.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lepto",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Leptospermum",0.79,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Leucodendron",0.75,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Liatris",0.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Liatris, spray",0.83,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lilies, Asiatic",1.40,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lilies, L.A. Hybrid",1.48,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lilies, Oriental",2.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lilies, Stargazer",2.20,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lily Grass",0.19,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lisanthus",1.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Lysamachia",1.29,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Magnolia",2.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Matsamota Aster",0.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Millet Grass",0.79,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Million Star",0.70,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ming Fern",0.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Misty",0.83,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Misty Statice",0.79,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Montbreesia (Crocosmia)",0.65,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Montbressia Pods (Crocosmia)",0.79,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Monte Casino",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Moss, Sheet",30.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Myrtle",0.59,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Nagi Fern",0.49,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Nandina",1.20,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Nigella",0.73,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Orchid, Dendrobium (each)",1.80,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Orchid, Jamestory (5 stem)",1.75,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Orchid, Mokara (5 stem)",1.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oregonia",0.70,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ornamental Peppers (5 stem)",1.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Parvafolia",0.63,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pepperberry",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Phalenopsis" ,3.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Phlox",0.79,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Photina",0.90,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pincusion Protea (each)",3.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pittosporum variegated",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pixies",0.30,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Plumosa Fern",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Podocarpus",0.63,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pumpkin Tree (5 stem)",1.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pumpkins Large (each)",4.19,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pumpkins/gourds mini (each)",0.39,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pyracantha Berry (5 stem)",1.90,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Queen Anne's Lace",0.95,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ranuculus",1.20,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Roses, 50cm straight colors special orders (25 stem)",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Roses, Red 40cm short stem (25 stem)",0.51,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Roses, Long Stem (25 stem)",1.10,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Roses, Rainbow packs short stem (25 stem)",0.43,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Roses, Spray ",1.20,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Roses, Sweethearts",1.05,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Rover",0.93,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ruscus",0.85,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Safari Sunset",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Safflower",1.09,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Salal",0.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Scabiosa",0.75,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Scotch Broom",4.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Sea Oats",0.77,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Sedum",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Smokebush",0.79,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Snapdragons",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Snowberry",1.25,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Solidago",0.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Spider Mums",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Spring Aster",0.60,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Springerii",0.85,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Star of Bethleham, orange",0.65,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Statice",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Stephanotis (25 pack)",1.25,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Sterling Range",0.75,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Stock",0.73,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Succulents",2.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Sunflowers (5 stem)",1.65,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Sunflowers, mini (5 stem)",1.50,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Sweet William",0.58,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Tanzy",0.83,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Thistle",1.78,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ti Leaves",0.41,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Toadlilies",1.30,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Trachelium",1.01,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Tree Fern, 20 bu",0.45,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Tritoma",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Tropical Leaves (count in 10's)",0.55,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Tulips",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Tulips, French",2.00,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Viburnum",2.43,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Waxflower",0.98,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Weigela",0.99,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Wheat",0.18,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Winterpink",0.64,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Yarrow",0.81,1);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Zinnia (each)",0.40,1);

/* Hard Goods */
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Arrive Alives (100/pkg)",0.69,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bouquet Holder, cascade grande",2.15,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bouquet Holder, Gala clear Large",9.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bouquet Holder, Gala clear small",4.46,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bouquet Holder, grande straight handle",2.15,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bouquet holder, large straight handle 1131720",1.45,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Bouquet Holder, medium Straight handle",1.29,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Candles, 3 pillar",3.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Candles, 6 pillar",6.80,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Candles, 9 Pillar",9.90,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Candles, Floating 2",0.92,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Candles, Floating 3",1.60,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Clear dishes, 11",3.25,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Clear dishes, 6",1.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Bud Vase 7.5 x 1.5 (4002-24-09)",2.44,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 10 1/2 x 3 1/2  (889)",3.10,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 10 x 4 3/4",2.87,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 4x4 ( 3101-12-09)",2.73,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 6 x 3 1/2 (974)/ 884",2.29,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 6 x 6 (3378-06-09)",2.18,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 7 1/2 x 3.5 (C007)",5.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Cylinder Vase 9 (C975)/ 888",2.04,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Deco Oasis",1.15,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Diamond Wristlet",5.00,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Floral Cage Grande",4.25,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Floral Iglu cage, large",2.00,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Floral Iglu cage, small",1.45,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl #11 WE390701",6.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl #5",6.50,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl #6",2.50,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl #7",3.25,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl #8",3.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl #9 WE380801",6.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Design Bowl WE370501",1.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache One Brick Tray WE90601",2.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Recreation 5",2.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Recreation 6 we390201",3.25,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Mache Recreation 7",3.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis deisgn ring 13 (with tray)",11.25,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis design ring 10 (with tray)",7.65,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis design ring 14 (with tray)",11.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Foam Blocks",0.76,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Raquette 12",3.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Raquette 18",6.75,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Raquette 27",8.75,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Raquette 36",9.85,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Wreath 18",19.00,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Wreath 22",22.00,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Oasis Wreath 24",26.45,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pearl Wristlet",2.50,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Pew Clips",0.75,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Ribbon",0.55,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Riviera Vase 12  (C929)",10.40,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Spray Paint",7.95,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Spring Garden Vase 11",7.00,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Styrofoam ball 3",0.75,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Styrofoam ball 4",1.00,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Styrofoam ball 6",3.25,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Vase Valet",1.73,2);
INSERT INTO proj_flowerapp.inventory (name, price, type) VALUES ("Vintage bud vases, clear (3203-24-09)",1.80,2);
